module.exports = {
  collectCoverage: true,
  collectCoverageFrom: [
    '<rootDir>/src/components/**/*.js',
    '<rootDir>/src/hocs/**/*.js',
    '<rootDir>/src/layouts/**/*.js',
    '<rootDir>/src/pages/**/*.js',
    '<rootDir>/src/utils/*.js',
    '!<rootDir>/src/pages/section/index.js',
    '!<rootDir>/src/components/molecules/navigation/index.js',
    '!<rootDir>/src/components/atoms/select/reactSelectCustomStyles.js',
  ],
  coverageDirectory: '<rootDir>/coverage',
  rootDir: './',
  moduleNameMapper: {
    '\\.(css)$': 'identity-obj-proxy',
    '\\.(svg)$': '<rootDir>/__mocks__/fileMock.js',
    '^Assets(.*)$': '<rootDir>/src/assets/$1',
    '^Components(.*)$': '<rootDir>/src/components/$1',
    '^Constants(.*)$': '<rootDir>/src/constants.js',
    '^Contexts(.*)$': '<rootDir>/src/contexts/$1',
    '^Fixtures(.*)$': '<rootDir>/__fixtures__/$1',
    '^Hocs(.*)$': '<rootDir>/src/hocs/$1',
    '^Layouts(.*)$': '<rootDir>/src/layouts/$1',
    '^Services(.*)$': '<rootDir>/src/services/$1',
    '^Utils(.*)$': '<rootDir>/src/utils/$1',
  },
  setupFiles: [
    '<rootDir>/src/config/setuptests.js',
  ],
  snapshotSerializers: ['enzyme-to-json/serializer'],
  transform: { '^.+\\.js$': 'babel-jest' },
  verbose: false,
};
