module.exports = [
  {
    url: 'https://static01.nyt.com/images/2018/12/15/science/15TB-DUCKWEED1/15TB-DUCKWEED1-thumbStandard.jpg',
    format: 'Standard Thumbnail',
    height: 75,
    width: 75,
    type: 'image',
    subtype: 'photo',
    caption: 'Duckweed, and a duck, on a pond in Germany.',
    copyright: 'Kay Nietfeld/DPA, via Getty Images',
  },
  {
    url: 'https://static01.nyt.com/images/2018/12/15/science/15TB-DUCKWEED1/15TB-DUCKWEED1-thumbLarge.jpg',
    format: 'thumbLarge',
    height: 150,
    width: 150,
    type: 'image',
    subtype: 'photo',
    caption: 'Duckweed, and a duck, on a pond in Germany.',
    copyright: 'Kay Nietfeld/DPA, via Getty Images',
  },
  {
    url: 'https://static01.nyt.com/images/2018/12/15/science/15TB-DUCKWEED1/15TB-DUCKWEED1-articleInline.jpg',
    format: 'Normal',
    height: 126,
    width: 190,
    type: 'image',
    subtype: 'photo',
    caption: 'Duckweed, and a duck, on a pond in Germany.',
    copyright: 'Kay Nietfeld/DPA, via Getty Images',
  },
  {
    url: 'https://static01.nyt.com/images/2018/12/15/science/15TB-DUCKWEED1/15TB-DUCKWEED1-mediumThreeByTwo210.jpg',
    format: 'mediumThreeByTwo210',
    height: 140,
    width: 210,
    type: 'image',
    subtype: 'photo',
    caption: 'Duckweed, and a duck, on a pond in Germany.',
    copyright: 'Kay Nietfeld/DPA, via Getty Images',
  },
  {
    url: 'https://static01.nyt.com/images/2018/12/15/science/15TB-DUCKWEED1/15TB-DUCKWEED1-superJumbo.jpg',
    format: 'superJumbo',
    height: 1364,
    width: 2048,
    type: 'image',
    subtype: 'photo',
    caption: 'Duckweed, and a duck, on a pond in Germany.',
    copyright: 'Kay Nietfeld/DPA, via Getty Images',
  },
];
