module.exports = [
  {
    section: 'Science',
    subsection: '',
    title: 'One of Natureu2019s Smallest Flowering Plants Can Survive Inside of a Duck',
    abstract: 'If one duckweed lands where a bird relieves itself, itu2019s capable of eventually creating a dense mat of duckweeds where there were none before.',
    url: 'https://www.nytimes.com/2018/12/14/science/duckweed-duck-poop.html',
    byline: 'By VERONIQUE GREENWOOD',
    item_type: 'Article',
    updated_date: '2018-12-14T09:32:51-05:00',
    created_date: '2018-12-14T09:32:50-05:00',
    published_date: '2018-12-14T09:32:50-05:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [
      'Flowers and Plants',
      'Invasive Species',
      'Weeds',
      'Birds',
      'Ducks',
      'Feces',
      'Wetlands',
    ],
    org_facet: [
      'Biology Letters (Journal)',
    ],
    per_facet: [
      'Green, Andy',
      'Silva, Giliandro',
    ],
    geo_facet: [
      'Brazil',
      'Great Britain',
      'Spain',
    ],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2018/12/15/science/15TB-DUCKWEED1/15TB-DUCKWEED1-thumbStandard.jpg',
        format: 'Standard Thumbnail',
        height: 75,
        width: 75,
        type: 'image',
        subtype: 'photo',
        caption: 'Duckweed, and a duck, on a pond in Germany.',
        copyright: 'Kay Nietfeld/DPA, via Getty Images',
      },
      {
        url: 'https://static01.nyt.com/images/2018/12/15/science/15TB-DUCKWEED1/15TB-DUCKWEED1-thumbLarge.jpg',
        format: 'thumbLarge',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption: 'Duckweed, and a duck, on a pond in Germany.',
        copyright: 'Kay Nietfeld/DPA, via Getty Images',
      },
      {
        url: 'https://static01.nyt.com/images/2018/12/15/science/15TB-DUCKWEED1/15TB-DUCKWEED1-articleInline.jpg',
        format: 'Normal',
        height: 126,
        width: 190,
        type: 'image',
        subtype: 'photo',
        caption: 'Duckweed, and a duck, on a pond in Germany.',
        copyright: 'Kay Nietfeld/DPA, via Getty Images',
      },
      {
        url: 'https://static01.nyt.com/images/2018/12/15/science/15TB-DUCKWEED1/15TB-DUCKWEED1-mediumThreeByTwo210.jpg',
        format: 'mediumThreeByTwo210',
        height: 140,
        width: 210,
        type: 'image',
        subtype: 'photo',
        caption: 'Duckweed, and a duck, on a pond in Germany.',
        copyright: 'Kay Nietfeld/DPA, via Getty Images',
      },
      {
        url: 'https://static01.nyt.com/images/2018/12/15/science/15TB-DUCKWEED1/15TB-DUCKWEED1-superJumbo.jpg',
        format: 'superJumbo',
        height: 1364,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption: 'Duckweed, and a duck, on a pond in Germany.',
        copyright: 'Kay Nietfeld/DPA, via Getty Images',
      },
    ],
    short_url: 'https://nyti.ms/2A0qiLp',
  },
  {
    section: 'Science',
    subsection: '',
    title: 'A Salamander of Legend Emerges From Southern Swamps',
    abstract: 'The reticulated siren is the largest vertebrate discovered in the United States in decades.',
    url: 'https://www.nytimes.com/2018/12/14/science/salamander-reticulated-siren.html',
    byline: 'By ASHER ELBEIN',
    item_type: 'Article',
    updated_date: '2018-12-14T13:01:09-05:00',
    created_date: '2018-12-14T13:01:09-05:00',
    published_date: '2018-12-14T13:01:09-05:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [
      'Salamanders',
      'Amphibians',
      'Biology and Biochemistry',
      'Reptiles',
    ],
    org_facet: [],
    per_facet: [],
    geo_facet: [
      'Alabama',
      'Florida',
    ],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2018/12/18/science/18SCI-SALAMANDER1/18SCI-SALAMANDER1-thumbStandard-v2.jpg',
        format: 'Standard Thumbnail',
        height: 75,
        width: 75,
        type: 'image',
        subtype: 'photo',
        caption: 'The newest named salamander in the animal kingdom: the reticulated siren.',
        copyright: 'David Steen',
      },
      {
        url: 'https://static01.nyt.com/images/2018/12/18/science/18SCI-SALAMANDER1/18SCI-SALAMANDER1-thumbLarge-v2.jpg',
        format: 'thumbLarge',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption: 'The newest named salamander in the animal kingdom: the reticulated siren.',
        copyright: 'David Steen',
      },
      {
        url: 'https://static01.nyt.com/images/2018/12/18/science/18SCI-SALAMANDER1/18SCI-SALAMANDER1-articleInline-v2.jpg',
        format: 'Normal',
        height: 127,
        width: 190,
        type: 'image',
        subtype: 'photo',
        caption: 'The newest named salamander in the animal kingdom: the reticulated siren.',
        copyright: 'David Steen',
      },
      {
        url: 'https://static01.nyt.com/images/2018/12/18/science/18SCI-SALAMANDER1/18SCI-SALAMANDER1-mediumThreeByTwo210-v2.jpg',
        format: 'mediumThreeByTwo210',
        height: 140,
        width: 210,
        type: 'image',
        subtype: 'photo',
        caption: 'The newest named salamander in the animal kingdom: the reticulated siren.',
        copyright: 'David Steen',
      },
      {
        url: 'https://static01.nyt.com/images/2018/12/18/science/18SCI-SALAMANDER1/18SCI-SALAMANDER1-superJumbo-v2.jpg',
        format: 'superJumbo',
        height: 1365,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption: 'The newest named salamander in the animal kingdom: the reticulated siren.',
        copyright: 'David Steen',
      },
    ],
    short_url: 'https://nyti.ms/2zYXp2d',
  },
  {
    section: 'Science',
    subsection: '',
    title: 'A Bright Green u2018Christmas Cometu2019 Will Fly the Closest to Earth in Centuries',
    abstract: 'The comet, called 46P/Wirtanen, will streak near Earth on Sunday and be visible in some places with the naked eye.',
    url: 'https://www.nytimes.com/2018/12/15/science/green-comet-46p-wirtanen.html',
    byline: 'By CHRISTINA CARON',
    item_type: 'Article',
    updated_date: '2018-12-15T19:28:59-05:00',
    created_date: '2018-12-15T14:09:49-05:00',
    published_date: '2018-12-15T14:09:49-05:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [
      'Comets',
      '46P/Wirtanen',
      'Space and Astronomy',
    ],
    org_facet: [
      'National Aeronautics and Space Administration',
    ],
    per_facet: [],
    geo_facet: [],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2018/12/16/autossell/16xp-comet/16xp-comet-thumbStandard.jpg',
        format: 'Standard Thumbnail',
        height: 75,
        width: 75,
        type: 'image',
        subtype: 'photo',
        caption: 'The comet 46P/Wirtanen as seen from France through a telescope this month.',
        copyright: 'Nicolas Biver/Agence France-Presse u2014 Getty Images',
      },
      {
        url: 'https://static01.nyt.com/images/2018/12/16/autossell/16xp-comet/16xp-comet-thumbLarge.jpg',
        format: 'thumbLarge',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption: 'The comet 46P/Wirtanen as seen from France through a telescope this month.',
        copyright: 'Nicolas Biver/Agence France-Presse u2014 Getty Images',
      },
      {
        url: 'https://static01.nyt.com/images/2018/12/16/autossell/16xp-comet/16xp-comet-articleInline.jpg',
        format: 'Normal',
        height: 127,
        width: 190,
        type: 'image',
        subtype: 'photo',
        caption: 'The comet 46P/Wirtanen as seen from France through a telescope this month.',
        copyright: 'Nicolas Biver/Agence France-Presse u2014 Getty Images',
      },
      {
        url: 'https://static01.nyt.com/images/2018/12/16/autossell/16xp-comet/merlin_148053384_83232fbc-01e3-4452-aa60-cc085f53bf69-mediumThreeByTwo210.jpg',
        format: 'mediumThreeByTwo210',
        height: 140,
        width: 210,
        type: 'image',
        subtype: 'photo',
        caption: 'The comet 46P/Wirtanen as seen from France through a telescope this month.',
        copyright: 'Nicolas Biver/Agence France-Presse u2014 Getty Images',
      },
      {
        url: 'https://static01.nyt.com/images/2018/12/16/autossell/16xp-comet/16xp-comet-superJumbo.jpg',
        format: 'superJumbo',
        height: 1365,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption: 'The comet 46P/Wirtanen as seen from France through a telescope this month.',
        copyright: 'Nicolas Biver/Agence France-Presse u2014 Getty Images',
      },
    ],
    short_url: 'https://nyti.ms/2En2PqK',
  },
];
